### ISSUE TITLE
[rp] signs not working

### ISSUE THREAD

**Issue by malbosia2013** [FabioZumbi12/RedProtect#10]
i cant figure it out, but the [rp] signs will not work. when you create an [rp] sign, it just creates and acts like a normal sign, and it doesnt show any error in the console log. any idea what might be causing this?

list of plugins i use:
Announcer
Antishare
Areashop
Asyncworldedit
Autorank
Builder
ChairStairs
ChestShop
Citizens
Citygates
Commandspy
CoreProtect
Dropedit
Dynmap
Dynmap-essentials
Enderspawn
Enjinminecraftplugin
Essentials
GAListener
GroupManager
HolographicDisplays
Lift
Liftsign
LWC
MassiveCore
OnTime
PluginMetrics
RedProtect
Sentry
Signeditor
SimpleCensor
SuperVanish
Updater
Vault
Votifier
WorldBorder
WorldEdit
WorldGuard

**Comment by malbosia2013** [comment]
also, i just tried using /rp list and got this in console:

09.12 10:25:11 [Multicraft] Skipped 10 lines due to rate limit (30/s)
09.12 10:25:00 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_05]
09.12 10:25:00 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_05]
09.12 10:25:00 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_05]
09.12 10:25:00 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_05]
09.12 10:25:00 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonParser
09.12 10:25:00 [Server] INFO ... 14 more
09.12 10:25:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at br.net.fabiozumbi12.RedProtect.RPCommands.onCommand(RPCommands.java:1305) ~[?:?]
09.12 10:25:00 [Server] INFO at br.net.fabiozumbi12.RedProtect.RPCommands.handleList(RPCommands.java:1859) ~[?:?]
09.12 10:25:00 [Server] INFO at br.net.fabiozumbi12.RedProtect.RPCommands.getRegionforList(RPCommands.java:1887) ~[?:?]
09.12 10:25:00 [Server] INFO at br.net.fabiozumbi12.RedProtect.Fanciful.FancyMessage.<clinit>(FancyMessage.java:773) ~[?:?]
09.12 10:25:00 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/google/gson/JsonParser
09.12 10:25:00 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
09.12 10:25:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.12 10:25:00 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v6.3.5
09.12 10:25:00 [Server] ERROR null
09.12 10:25:00 [Server] INFO devilsadvocate issued server command: /rp list

**Comment by FabioZumbi12** [comment]
The error om /rp list its because your server version dont support "json" events, then you need to disable the "region-settings > region-list > hover-and-click-teleport".

About create a rp sign, i will fix

**Comment by FabioZumbi12** [comment]
Fixed on this version: http://dev.bukkit.org/media/files/904/952/RedProtect.jar

**Comment by malbosia2013** [comment]
im using that version, its still not working. imma restart my server and send a pastbin of the full start up log so so can see

**Comment by malbosia2013** [comment]
http://pastebin.com/yTRdcXYq

**Comment by FabioZumbi12** [comment]
This error is not with Redprotect! You do the command "/list" and not "/rp list"

...and no errors including RedProtect Classes, only others!
