### ISSUE TITLE
Issue : Size for redefine

### ISSUE THREAD

**Issue by NicolasDelahaigue** [FabioZumbi12/RedProtect#175]
PaperSpigot 1.11.2
RedProtect 7.1.4 b367
Minecraft 1.11.2

**Issue :**

When I want to redefine a region the plugin need the new size in addition of the old size. Normally, I should have available the difference between the old and the new size. 

**Example :**

Assuming that the RP Limit is 1000 blocks.
If I have a region of 1000 blocks and I want to reduce the region size to 800 blocks I should normally have enough blocks but the plugin need 800 blocks more. If I want the redefine to work I should have an RP Limit of at least 1800 blocks.

**Comment by FabioZumbi12** [comment]
Try the latest version from Jenkins http://areaz12server.net.br:8080/job/RedProtect/

I found a code where can change this (i already fixed this later for some situations)

**Comment by aurel85** [comment]
We have tested and the problem is still there.

Moreover, when we do /rp flag there is an error: https://pastebin.com/Ffq6hDnW

**Comment by FabioZumbi12** [comment]
Download the latest build. I move to Protocollib to remove /rp flag atributes.

**Comment by aurel85** [comment]
This is ok for the /rp flag with b377. Okay, good luck !

**Comment by FabioZumbi12** [comment]
I fixed the region size problem for spigot and is know still on sponge. Reopen if not fixed. (download latest from jenkins)

**Comment by aurel85** [comment]
The problem is always present in the version b398.
