### ISSUE TITLE
[Suggestion] UUID storage with online-mode false

### ISSUE THREAD

**Issue by Dakir22** [FabioZumbi12/RedProtect#397]
Hi, is it possible that the claim members with the UUID are stored in the config even if the offline mode is set to false? Because I use a bungeecord server that runs online-mode true and if someone renames themselves you have to transfer the claims again and again to the new name.

**Comment by FabioZumbi12** [comment]
Added option on a9693f - try the latest dev build.

**Comment by Dakir22** [comment]
Thank you, it works.
I only have one more question.
Since so far all regions have been saved with the name and not with the UUIDS, the old regions are no longer recognized. 
Is there a way to automatically convert all player names to UUIDs?

**Comment by FabioZumbi12** [comment]
Yeah, theres an option on config, on `hooks` section to convert all name to uiids, just make a backup of your db and enable this option, and then restart the server

**Comment by Dakir22** [comment]
Thanks for the quick answer.
I just changed it and then started the server and then it started but stopped immediately because an ERROR occurred.

ERROR: http://prntscr.com/n7n2x0

Could it be that there is no current UUID for a playername because the user already renamed himself and then stops the whole process? Because there are about 500 regions in total.

**Comment by FabioZumbi12** [comment]
Done on https://github.com/FabioZumbi12/RedProtect/commit/8fb307d7414f89c50ee12564879868ceba98ba96, try with the latest version

**Comment by Dakir22** [comment]
Screen: http://prntscr.com/n7suiu

Hi, I tested it again. 
Unfortunately the error came back after some names were converted. In the screen the last name he wanted to convert is the name "shot down" and since this player had renamed himself the name is available again and has no current UUID but in the console:
`[10:26:20 INFO]: [RedProtect] Leader from: abgeschossenyt
[10:26:20 INFO]: [RedProtect] To UUID: 096abf08-a012-365c-917b-353a44c2f0dd`

This UUID does not exist.
Could it be that this is the reason?

**Comment by FabioZumbi12** [comment]
probally yes, if the people changed the nickname before this migration i think you need to change manually for all player regions. Using notepad++ you can do this easily.

**Comment by Dakir22** [comment]
Ok many thanks for your help
