### ISSUE TITLE
[BUG] Particular name of the claim is reset after a reboot

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#572]
Hi,

I use the last version of this plugin (295) and Paper 1.15.2 (86).

I could see that we could not give a name to less than 3 characters during the /rp claim and not less than 4 characters during the /rp rename.
Problem if I name my claim "Hub" during its creation it will become again a classic name "aurel85_0" after a reboot of the server.
This character limit is not a problem for me but it would have to be operational to avoid names being reset, so that the /rp claim and the /rp rename limit the name of the claim to at least 3 characters, that they are at same level.

Thank you in advance.

**Comment by FabioZumbi12** [comment]
Fixed the diff between bot commands on next dev build

**Comment by aurel85** [comment]
I can still name my claim Hub but after the reboot it becomes aurel85_0 again, same for /rp rename Hub. I think there is still a problem.
Re-open please.

**Comment by aurel85** [comment]
It's ok with version 305, thank you !
